/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package organizationeventmangementsystem;

/**
 *
 * @author Hillol Talukdar
 */
public class OrganizationEventMangementSystem extends javax.swing.JFrame {

    /**
     * Creates new form OrganizationEventMangementSystem
     */
    public OrganizationEventMangementSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        organaizationjButton = new javax.swing.JButton();
        servicejButton = new javax.swing.JButton();
        reservationjButton = new javax.swing.JButton();
        customerjButton = new javax.swing.JButton();
        staffjButton = new javax.swing.JButton();
        orderjButton = new javax.swing.JButton();
        food_menujButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        organaizationjButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        organaizationjButton.setText("Organaization");
        organaizationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organaizationjButtonActionPerformed(evt);
            }
        });

        servicejButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        servicejButton.setText("Service");
        servicejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicejButtonActionPerformed(evt);
            }
        });

        reservationjButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        reservationjButton.setText("Reservation");
        reservationjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationjButtonActionPerformed(evt);
            }
        });

        customerjButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        customerjButton.setText("Customer");
        customerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerjButtonActionPerformed(evt);
            }
        });

        staffjButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        staffjButton.setText("Staff");
        staffjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffjButtonActionPerformed(evt);
            }
        });

        orderjButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        orderjButton.setText("Order");
        orderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderjButtonActionPerformed(evt);
            }
        });

        food_menujButton.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        food_menujButton.setText("Food Menu");
        food_menujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_menujButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Organization Event Mangement System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(organaizationjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(servicejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(reservationjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(orderjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(food_menujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(staffjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(customerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organaizationjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(servicejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(staffjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(food_menujButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(reservationjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(orderjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void organaizationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organaizationjButtonActionPerformed
        // TODO add your handling code here:
        organaization org = new organaization();

       org.setVisible(true);
        
    }//GEN-LAST:event_organaizationjButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        this.setSize(1400, 750);
        this.setTitle("Organization Event Mangement System");
    }//GEN-LAST:event_formWindowActivated

    private void servicejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicejButtonActionPerformed

        
        Service service = new Service();
        
        service.setTitle("Service");
        service.setVisible(true);
        
        service.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_servicejButtonActionPerformed

    private void staffjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffjButtonActionPerformed

        Staff staff = new Staff();
        staff.setTitle("Staff");
        staff.setVisible(true);
    }//GEN-LAST:event_staffjButtonActionPerformed

    private void customerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerjButtonActionPerformed
       
        Customer customer = new Customer();
        customer.setTitle("Customer");
        customer.setVisible(true);
    }//GEN-LAST:event_customerjButtonActionPerformed

    private void reservationjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationjButtonActionPerformed
        Reservation reservation = new Reservation();
        reservation.setTitle("Reservation");
        reservation.setVisible(true);
    }//GEN-LAST:event_reservationjButtonActionPerformed

    private void orderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderjButtonActionPerformed
        Order order = new Order();
        order.setTitle("Order");
        order.setVisible(true);
    }//GEN-LAST:event_orderjButtonActionPerformed

    private void food_menujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_menujButtonActionPerformed
        FoodMenu foodMenu = new FoodMenu();
        foodMenu.setTitle("Food Menu");
        foodMenu.setSize(1400, 750);
        foodMenu.setVisible(true);
    }//GEN-LAST:event_food_menujButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrganizationEventMangementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrganizationEventMangementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrganizationEventMangementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrganizationEventMangementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrganizationEventMangementSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerjButton;
    private javax.swing.JButton food_menujButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton orderjButton;
    private javax.swing.JButton organaizationjButton;
    private javax.swing.JButton reservationjButton;
    private javax.swing.JButton servicejButton;
    private javax.swing.JButton staffjButton;
    // End of variables declaration//GEN-END:variables
}
